@baseUrl = http://localhost:8080/exercise35/students

### Get all students
GET {{baseUrl}}
Accept: application/json


### Create student successfully
POST {{baseUrl}}
Content-Type: application/json

{
    "name": "Lara",
    "role": "Raider"
}


### Check the updated student list
GET {{baseUrl}}
Accept: application/json